/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:695f9233-fa9d-44da-b9c0-4c1498a46e78",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_wguXO923D",
    "aws_user_pools_web_client_id": "66t2s4g7rbkr43ir771tckodc7",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://rhc24t3thrh6xod37jfnvkkide.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-vrhohyjvrrcvtdy6gpukv2hf3u",
    "aws_user_files_s3_bucket": "amplifyappc2883c0a4e644db685e90c438b60311b215914-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
